### ISSUE TITLE
[Epic] Add GraphQL client generation tool to Ballerina distribution

### ISSUE THREAD

**Issue by RolandHewage** [ballerina-platform/graphql-tools#42]
**Description:**
We need to address the following issues to add the GraphQL client generation tool to Ballerina distribution

- [x] https://github.com/ballerina-platform/graphql-tools/issues/36
- [x] https://github.com/ballerina-platform/graphql-tools/issues/38
- [x] https://github.com/ballerina-platform/graphql-tools/issues/39
- [x] https://github.com/ballerina-platform/graphql-tools/issues/40
- [x] https://github.com/ballerina-platform/graphql-tools/issues/41

**Suggested Labels:**

**Comment by RolandHewage** [comment]
Closing this issue since all the tasks are completed
